tharwoodyy/Classic-Cars

Gemfile
Gemfile.lock
app/controllers/cars_controller.rb
app/models/booking.rb
app/models/car.rb
app/models/user.rb
app/views/layouts/application.html.erb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20200224141839_devise_create_users.rb
db/migrate/20200224142512_create_cars.rb
db/migrate/20200224142554_create_bookings.rb
db/schema.rb
test/controllers/cars_controller_test.rb
test/models/booking_test.rb
test/models/car_test.rb
test/models/user_test.rb

completed devise setup, created a user model and cars controller

completed setup, models and cars controller

---

app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show.scss
app/views/cars/show.html.erb
db/seeds.rb

Update the show page, skeleton html, added images and a _show.scss file.

show page updated

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/controllers/cars_controller.rb
app/views/cars/index.html.erb
app/views/layouts/application.html.erb
db/seeds.rb

Completed index.html.erb 
styled the card in stylesheet --> components --> _card.scss

Index view

---

app/assets/stylesheets/components/_card.scss
app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb

added sign up  feature using devise

sign in complete

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_show.scss
app/views/cars/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

Hi team,
Navbar, footer added, plus homepage and show layouts updated.

Navbar, footer, and homepage layout updated

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_card.scss
app/controllers/cars_controller.rb
app/models/car.rb
app/views/cars/index.html.erb
app/views/cars/new.html.erb
app/views/cars/show.html.erb
config/environment.rb
config/environments/development.rb
config/storage.yml
db/migrate/20200225115819_add_columns_to_cars.rb
db/migrate/20200225134817_create_active_storage_tables.active_storage.rb
db/schema.rb

Adding create

---

app/assets/stylesheets/pages/_login.scss

I added styling to the sign up page

signup styling complete

---

app/assets/stylesheets/components/_navbar.scss

I made the nav bar sticky so it looks good on the sign up page. please review

sticky navbar

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

Few further updates to nav and footer

further updated nav and footer

---

app/controllers/bookings_controller.rb
app/models/booking.rb
app/models/car.rb
app/views/bookings/index.html.erb
app/views/cars/show.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
test/controllers/bookings_controller_test.rb

made some changes to controller, added methods and created view files

Bookings controller

---

app/assets/stylesheets/components/_card.scss

added 50px to card, to give it more space and looks better on page

added padding

---

app/controllers/bookings_controller.rb
app/views/bookings/new.html.erb
config/routes.rb

Added the booking form, still need to work on the booking index.

booking form added

---

app/controllers/cars_controller.rb
app/controllers/reviews_controller.rb
app/models/car.rb
app/models/review.rb
app/views/cars/show.html.erb
app/views/reviews/_new.html.erb
config/routes.rb
db/migrate/20200227114835_create_reviews.rb
db/schema.rb
test/controllers/reviews_controller_test.rb
test/models/review_test.rb

completed the backend for reviews, will work on frontend now

completed backend

---

Gemfile
Gemfile.lock
app/controllers/bookings_controller.rb
app/views/bookings/index.html.erb
app/views/bookings/new.html.erb
app/views/cars/show.html.erb
config/routes.rb

Needs styling but we have calendar input on the booking form, a bookings index for the user to see all their current bookings, and the ability to cancel bookings if they want.

Added booking index and ability to cancel

---

app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/controllers/cars_controller.rb
app/controllers/reviews_controller.rb
app/models/user.rb
app/views/cars/show.html.erb
app/views/reviews/_new.html.erb
config/routes.rb

made changes to reviews, linked them through association bookings. Also, added user authorization (not using pundit)!

review changes and access changes

---

app/controllers/cars_controller.rb

fixed show bug

---

app/controllers/application_controller.rb
app/controllers/cars_controller.rb
app/controllers/reviews_controller.rb
app/views/cars/show.html.erb
config/routes.rb

changes to destroy method, all working now! and user access

destroy reviews and user

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show.scss
app/assets/stylesheets/pages/new.scss
app/views/bookings/new.html.erb
app/views/cars/index.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

added images but havent finished

styling the booking page

---

app/assets/stylesheets/pages/_show.scss
app/views/cars/show.html.erb

the styling is done :) will style reviews after!

show page is good to go, styling is done

---

app/assets/stylesheets/pages/_booking.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/views/bookings/index.html.erb

Card shows up for each booking, and the delete booking function now works

added cards for each booking on the index page

---

app/assets/stylesheets/pages/_show.scss
app/assets/stylesheets/pages/new.scss
app/views/bookings/new.html.erb
app/views/cars/show.html.erb

finished booking

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/new.scss

fixed the form padding and did final check
